name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 👀
        uses: actions/checkout@v4

      - name: Set up NodeJS 📦
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies 📦
        run: npm install

      - name: Build the project 🔨
        run: npm run build

      - name: Run tests 🚨
        run: npm test

      - name: Notify by SMS
        run: |
          response=$(curl -s --request POST \
            --url https://api.sarbacane.com/sendkit/sms/send/notification \
            --header "x-apiKey: ${{ secrets.API_KEY }}" \
            --header "Content-Type: application/json" \
            --data '{"number":"${{ secrets.PHONE_NUMBER }}","message":"CI/CD Pipeline.","sender":"Terabook CI/CD","campaignName":"CI/CD Pipeline","category":"CI/CD Pipeline"}')
          echo "response from curl= $response"

      - name: Get Test Post
        run: |
          response=$(curl https://jsonplaceholder.typicode.com/posts/7 \
            -H "Accept: application/json")
          echo "response from curl= $response"