name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 👀
        uses: actions/checkout@v4

      - name: Set up NodeJS 📦
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies 📦
        run: npm install

      - name: Build the project 🔨
        run: npm run build

      - name: Run tests 🚨
        run: npm test

      - name: Notify by SMS
        run: |
          response=$(curl -s --request POST \
            --url https://api.sarbacane.com/sendkit/sms/send/notification \
            --header "x-apiKey: 26yrvxaonr04ccmab9fbdmrka22chdi0du6cfgyogxqv" \
            --header "Content-Type: application/json" \
            --data '{"number":"+33766840493","message":"CI/CD Pipeline","sender":"YourCompany","campaignName":"Code de confirmation","category":"codeConfirmation"}')
          echo "response from curl = $response"