name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 👀
        uses: actions/checkout@v4

      - name: Set up NodeJS 📦
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies 📦
        run: npm install

      - name: Build the project 🔨
        run: npm run build

      - name: Run tests 🚨
        run: npm test

      - name: Notify by SMS
        run: |
          curl -X POST \
          -H "x-apiKey: ${{ secrets.API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"number":"${{ secrets.PHONE_NUMBER }}","message":"CI/CD Pipeline.","sender":"Terabook CI/CD","campaignName":"CI/CD Pipeline","category":"CI/CD Pipeline"}' \
          https://api.sarbacane.com/sendkit/sms/send/notification

        
